// ─── Pipeline Constants ─────────────────────────────────────────────────────────
// Hoisted outside any component — never re-created on render.

import {
    type BuyerPipelineStatus,
    type StageConfig,
    type PipelineLead,
} from "./pipelineTypes";

// ─── Stage configuration ─────────────────────────────────────────────────────────

export const STAGE_ORDER: BuyerPipelineStatus[] = [
    "new_lead",
    "contacted",
    "viewing",
    "negotiation",
    "won",
    "lost",
];

export const STAGE_CONFIG: Record<BuyerPipelineStatus, StageConfig> = {
    new_lead: {
        status: "new_lead",
        label: "New Lead",
        color: "bg-blue-50",
        textColor: "text-blue-600",
        borderColor: "border-blue-200",
        columnBg: "bg-blue-50/60",
        dotColor: "bg-blue-500",
    },
    contacted: {
        status: "contacted",
        label: "Contacted",
        color: "bg-amber-50",
        textColor: "text-amber-600",
        borderColor: "border-amber-200",
        columnBg: "bg-amber-50/60",
        dotColor: "bg-amber-500",
    },
    viewing: {
        status: "viewing",
        label: "Viewing",
        color: "bg-violet-50",
        textColor: "text-violet-600",
        borderColor: "border-violet-200",
        columnBg: "bg-violet-50/60",
        dotColor: "bg-violet-500",
    },
    negotiation: {
        status: "negotiation",
        label: "Negotiation",
        color: "bg-orange-50",
        textColor: "text-orange-600",
        borderColor: "border-orange-200",
        columnBg: "bg-orange-50/60",
        dotColor: "bg-orange-500",
    },
    won: {
        status: "won",
        label: "WON",
        color: "bg-emerald-50",
        textColor: "text-emerald-600",
        borderColor: "border-emerald-200",
        columnBg: "bg-emerald-50/60",
        dotColor: "bg-emerald-500",
    },
    lost: {
        status: "lost",
        label: "LOST",
        color: "bg-red-50",
        textColor: "text-red-500",
        borderColor: "border-red-200",
        columnBg: "bg-red-50/60",
        dotColor: "bg-red-500",
    },
};

// ─── Mock data ────────────────────────────────────────────────────────────────────

export const MOCK_LEADS: PipelineLead[] = [
    {
        id: "lead-1",
        name: "Pak Anton Wijaya",
        phone: "628123456789",
        email: "anton@email.com",
        propertyName: "Modern Villa Ubud",
        propertyLocation: "Ubud, Bali",
        propertyPrice: 850000,
        propertyCurrency: "USD",
        status: "new_lead",
        customerType: "buyer",
        source: "Instagram",
        createdAt: "2026-08-20T08:00:00Z",
        lastContacted: undefined,
    },
    {
        id: "lead-2",
        name: "Ibu Sari Putri",
        phone: "628987654321",
        propertyName: "Minimalist Villa Canggu",
        propertyLocation: "Canggu, Bali",
        propertyPrice: 35000,
        propertyCurrency: "USD",
        status: "contacted",
        customerType: "renter",
        source: "WhatsApp",
        createdAt: "2026-08-18T10:00:00Z",
        lastContacted: "2026-08-22T09:00:00Z",
    },
    {
        id: "lead-3",
        name: "David Tanaka",
        phone: "628111222333",
        email: "david.t@gmail.com",
        propertyName: "Beachfront Premium House",
        propertyLocation: "Seminyak, Bali",
        propertyPrice: 2100000,
        propertyCurrency: "USD",
        status: "viewing",
        customerType: "buyer",
        source: "Referral",
        createdAt: "2026-08-15T14:00:00Z",
        lastContacted: "2026-08-23T11:00:00Z",
    },
    {
        id: "lead-4",
        name: "Budi Santoso",
        phone: "628444555666",
        propertyName: "Tropical Garden Townhouse",
        propertyLocation: "Kerobokan, Bali",
        propertyPrice: 420000,
        propertyCurrency: "USD",
        status: "negotiation",
        customerType: "buyer",
        source: "Website",
        createdAt: "2026-08-10T09:00:00Z",
        lastContacted: "2026-08-25T08:00:00Z",
    },
    {
        id: "lead-5",
        name: "Lisa Chen",
        phone: "628777888999",
        email: "lisa.chen@company.com",
        propertyName: "Luxury Clifftop Villa",
        propertyLocation: "Uluwatu, Bali",
        propertyPrice: 3200000,
        propertyCurrency: "USD",
        status: "won",
        customerType: "buyer",
        source: "Google",
        createdAt: "2026-07-01T09:00:00Z",
        lastContacted: "2026-08-20T16:00:00Z",
    },
    {
        id: "lead-6",
        name: "Hendra Gunawan",
        phone: "628333444555",
        propertyName: "Strategic Commercial Land",
        propertyLocation: "Kuta, Bali",
        propertyPrice: 980000000,
        propertyCurrency: "IDR",
        status: "lost",
        customerType: "buyer",
        source: "TikTok",
        createdAt: "2026-08-01T09:00:00Z",
        lastContacted: "2026-08-19T10:00:00Z",
    },
    {
        id: "lead-7",
        name: "Mira Kusuma",
        phone: "628222333444",
        email: "mira@mail.com",
        propertyName: "Modern Villa Ubud",
        propertyLocation: "Ubud, Bali",
        propertyPrice: 850000,
        propertyCurrency: "USD",
        status: "new_lead",
        customerType: "renter",
        source: "Instagram",
        createdAt: "2026-08-24T07:00:00Z",
    },
    {
        id: "lead-8",
        name: "Robert Lim",
        phone: "628666777888",
        propertyName: "Minimalist Villa Canggu",
        propertyLocation: "Canggu, Bali",
        propertyPrice: 35000,
        propertyCurrency: "USD",
        status: "contacted",
        customerType: "buyer",
        source: "Referral",
        createdAt: "2026-08-16T09:00:00Z",
        lastContacted: "2026-08-21T14:00:00Z",
    },
];
